//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProfile
    {
        public string ProfileId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string HomeAddress { get; set; }
        public Nullable<int> CellNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string UserTypeId { get; set; }
    }
}
